### ISSUE TITLE
train

### ISSUE THREAD

**Issue by TianMingChen** [LinXiLuo/my_delf#2]
你好，你上传的代码好像不完整，能上传完整的代码吗?

**Comment by LinXiLuo** [comment]
目前上传的只是训练部分的代码，把training文件加到完整代码的python中就行了 ：）

**Comment by TianMingChen** [comment]
> 目前上传的只是训练部分的代码，把training文件加到完整代码的python中就行了 ：）

OK,thanks a lot !
